# Rename to `application.yml` and modify.
#
# Add application configuration variables here, as shown below.
# They will automatically be added to ENV locally, and will be
# pushed to heroku when you locally exec `rake figaro:heroku`
#
SECRET_KEY_BASE: long_hex_string

